language: ruby
rvm: 2.3.4
notifications:
  email: false
cache:
  - bundler
  - apt
addons:
  postgresql: '9.6'
before_install:
  - sudo apt-get update
  - sudo apt-get install -y postgresql-server-dev-9.6 libpq-dev
before_script:
  - psql -c 'CREATE DATABASE w3_assessment_test;' -U postgres
script:
  - bundle exec rspec
  - bundle exec cucumber
